filters:
  comments: true
  allowlist:
    allow:
      - "/\\$\\$?[\\s\\S]*?\\$\\$?/m"
      - "ｗ"
rules:
  preset-ja-spacing:
    ja-space-between-half-and-full-width:
      space: always
    ja-space-around-code:
      before: true
      after: true
  preset-ja-engineering-paper:
    prh: false
    use-si-units: false
    no-synonyms:
      allows:
        - "出し" # vs "だし"
    unify-kuten-and-touten:
      kuten: "。"
      touten: "、"
  preset-ja-technical-writing:
    max-ten: false
    max-comma: false
    no-mix-dearu-desumasu:
      preferInHeader: ""
      preferInBody: ""
      preferInList: ""
      strict: false
    ja-no-mixed-period: false
    no-exclamation-question-mark:
      allowFullWidthExclamation: true
      allowFullWidthQuestion: true
    no-hankaku-kana: false
    ja-no-weak-phrase: false
    ja-no-redundant-expression: false
    max-kanji-continuous-len: false
    no-doubled-joshi: false
    no-doubled-conjunctive-particle-ga: false
    no-doubled-conjunction: false
    no-unmatched-pair: false
    sentence-length: false
    ja-no-successive-word: false
  "@textlint-ja/no-insert-dropping-sa": true
  "@textlint-ja/no-dropping-i": true
  "@textlint-rule/no-invalid-control-character": true
  no-mixed-zenkaku-and-hankaku-alphabet: true
  no-dead-link:
    checkRelative: false
    retry: 1
  prefer-tari-tari: true
  terminology: true
  ja-no-inappropriate-words: true
  date-weekday-mismatch: true
  no-todo: true
  prh:
    checkEmphasis: true
    rulePaths: [./prh.yaml]
