on: pull_request

name: deploy preview

jobs:
  deploy_preview:
    name: Deploy preview
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: coord-e-com
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      # We need to move files in order to allow access via docker's volume mount
      - run: |
          mkdir dist
          cp -r result/* dist/
      - id: deploy_to_netlify
        uses: netlify/actions/cli@6c34c3fcafc69ac2e1d6dbf226560329c6dfc51b
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: '${{ secrets.NETLIFY_SITE_ID }}'
          NETLIFY_AUTH_TOKEN: '${{ secrets.NETLIFY_AUTH_TOKEN }}'
      - uses: actions/github-script@v3
        env:
          NETLIFY_URL: '${{ steps.deploy_to_netlify.outputs.NETLIFY_URL }}'
          NETLIFY_OUTPUT: '${{ steps.deploy_to_netlify.outputs.NETLIFY_OUTPUT }}'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: [
                  `Deploy preview ready: ${process.env.NETLIFY_URL}`,
                  '<details>',
                  '',
                  '```',
                  process.env.NETLIFY_OUTPUT,
                  '```',
                  '</details>'
                ].join('\n')
            })
