on:
  push:
    branches:
      - main

name: deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: coord-e-com
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      # We need to move files in order to allow access via docker's volume mount
      - run: |
          mkdir dist
          cp -r result/* dist/
      - uses: netlify/actions/cli@6c34c3fcafc69ac2e1d6dbf226560329c6dfc51b
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: '${{ secrets.NETLIFY_SITE_ID }}'
          NETLIFY_AUTH_TOKEN: '${{ secrets.NETLIFY_AUTH_TOKEN }}'
