on: push

name: deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: coord-e-com
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      - uses: cloudflare/pages-action@1
        with:
          apiToken: '${{ secrets.CLOUDFLARE_API_TOKEN }}'
          accountId: 0bb64cf424cd30c7424b29d601347db8
          projectName: coord-e-com
          directory: result
          gitHubToken: '${{ secrets.GITHUB_TOKEN }}'
